Remove dead code.

diff --git a/nvidia-unbound b/nvidia-unbound
--- a/nvidia-unbound
+++ b/nvidia-unbound
@@ -29,7 +29,7 @@ Options:
 
 	-q, --quiet
 		equivalent to --verbose=0
-		
+
 	-u, --use=PATH
 		use existing unpacked package at PATH
 
@@ -48,10 +48,10 @@ Options:
 
         -k, --kernel-name KERNEL_VERSION
 		compile specified kernel module only. Otherwise do all installed kernels
-      
+
 	-M, --kernel-module-type=KERNEL_MODULE_TYPE
 		Whether to build the "open" or "proprietary" drivers. If argument is ""
-		assume "open" if available, otherwise "proprietary". 
+		assume "open" if available, otherwise "proprietary".
 
 	-U, --no-kernel-modules[=BOOL}
 		install utilities and user libraries only
@@ -98,12 +98,12 @@ Options:
 
 	-I, --info
 		print information (meta-data) from the Nvidida driver archive
-		
+
 	-V, --version
 		print the $PROG version and exit (c.f. --info)
 
 	-h|--help)
-		print this text and exit	
+		print this text and exit
 "
 
 export TMPDIR=/var/tmp
@@ -240,7 +240,7 @@ function set_binary_opt(){
     local val
     local opt=${1#--}
     opt=${opt#no-}
-    
+
     if binary_opt_istrue "$2" "$3"; then
 	val=t
     else
@@ -427,7 +427,7 @@ done
 	value=${arg_map[$key]}
 	echo "$key = $value"
     done | sort -k 1,1
-    
+
     exit 0
 }
 
@@ -461,7 +461,7 @@ if [[ -n ${arg_map[log-path]} ]]; then
 fi
 
 
-if [[ -z ${arg_map[use]} ]]; then 
+if [[ -z ${arg_map[use]} ]]; then
     [[ -r $1 ]] || { error Cannot access $1; exit 1;}
 
     NVIDIA=$(mktemp -t -d NVIDIA.XXXXXXXX) || { error "$PROG Cannot allocate temporary directory";}
@@ -469,11 +469,11 @@ if [[ -z ${arg_map[use]} ]]; then
     trap "[[ -n \${manifest_fd} ]] &&  exec -- {manifest_fd}<&-; /bin/rm -rf ${NVIDIA}" EXIT
 
     pushd $NVIDIA; simple_cmd /bin/sh $1 -x; popd
-    
+
     NVIDIA_ROOT=$(echo $NVIDIA/*)
 else
     NVIDIA_ROOT=${arg_map[use]}
-    [[ -d ${NVIDIA_ROOT} ]] || { error "Missing ${NVIDIA_ROOT}"; exit 1;} 
+    [[ -d ${NVIDIA_ROOT} ]] || { error "Missing ${NVIDIA_ROOT}"; exit 1;}
 fi
 cd "$NVIDIA_ROOT"
 
@@ -502,13 +502,13 @@ function dkms_conf(){
 		PACKAGE_NAME="nvidia"
 		PACKAGE_VERSION="$release"
 		AUTOINSTALL="yes"
-		
+
 		# By default, DKMS will add KERNELRELEASE to the make command line; however,
 		# this will cause the kernel module build to infer that it was invoked via
 		# Kbuild directly instead of DKMS. The dkms(8) manual page recommends quoting
 		# the 'make' command name to suppress this behavior.
 		MAKE[0]="'make' -j`nproc` IGNORE_PREEMPT_RT_PRESENCE=1 NV_EXCLUDE_BUILD_MODULES='__EXCLUDE_MODULES' KERNEL_UNAME=\${kernelver} modules"
-		
+
 		# The list of kernel modules will be generated by nvidia-installer at runtime.
 	EOF
 	for module in "$@"; do
@@ -542,15 +542,15 @@ if [[ ${arg_map[kernel-modules-only]} != t ]]; then
 	done
 	return 1
     }
-    
+
     function exclude(){
-	if [[ ${arg_map[$1]} != t ]]; then 
+	if [[ ${arg_map[$1]} != t ]]; then
 	    exclude_list+=("${*@Q}")
 	fi
     }
 
     # Objects are excluded if the controlling option is false and all fields match the corresponding patternn
-    # 
+    #
     #	    Controlling								Additional
     #	    Option			File		Type			Path		Module
     # ------------------------------------------------------------------------------------------------
@@ -576,7 +576,7 @@ if [[ ${arg_map[kernel-modules-only]} != t ]]; then
 
     function encode(){ echo "${@@Q}";}
 
-    function inherit_path(){ 
+    function inherit_path(){
 	declare -i depth=${1#*:}
 	declare -a src_path
 	local src="${2%/*}"
@@ -687,7 +687,7 @@ if [[ ${arg_map[kernel-modules-only]} != t ]]; then
 	    warn "Unknown action type: $action_type. Skipping..."
 	    continue
 	fi
-	
+
 	eval action=($action_encoded)
 	work=${action[0]}
 	if [[ $work == noop ]]; then
@@ -740,13 +740,13 @@ if [[ ${arg_map[kernel-modules-only]} != t ]]; then
 	if (( remaining == 1 )); then
 	    dst+=${fields[i]#/}
 	fi
-	
+
 	if (( remaining == 2 )); then
 	    a=${fields[i]#/}
 	    a=${a%/}
 	    dst+=${a:+$a/}${fields[i+1]#/}
 	fi
-	
+
 	if (( remaining > 2 )); then
 	    warn "HELP too many fields"$'\n'"${fields[*]}"
 	fi
@@ -800,21 +800,9 @@ if [[ ${arg_map[kernel-modules-only]} != t ]]; then
 		    ;;
 	    esac
 	fi
-	
+
     done < <(sed -n '9,$p' "$NVIDIA_ROOT/.manifest" )
 fi
-
-if [[ "${arg_map[symlink]}" = t ]]; then
-    ln -s ${VPREFIX} ${PREFIX}/${release:0:1}XX
-fi
-    
-if [[ "${arg_map[symlink]}" = t ]]; then
-    if [ -h ${PREFIX}/latest${legacy:+-legacy} ]; then
-	/bin/rm ${PREFIX}/latest${legacy:+-legacy}
-    fi
-    ln -s ${VPREFIX} ${PREFIX}/latest${legacy:+-legacy}
-fi
-
 
 if [[ "${arg_map[kernel-modules]}" == t ]]; then
     set -x
@@ -834,7 +822,7 @@ if [[ "${arg_map[kernel-modules]}" == t ]]; then
 
     [[ -d $NVIDIA_ROOT/$build_dir ]] || { error cd:  $NVIDIA_ROOT/$build_dir: no such file or directory; exit 1;}
     cd $NVIDIA_ROOT/$build_dir
-    
+
     kernel_mod_success=
     for kernel_modlib in /lib/modules/${arg_map[kernel-name]:-*}; do
 	kernel_version=${kernel_modlib##*/}
